#!/usr/bin/env bash

# This script runs make in a docker container, so that you don't need to install
# the build tools on your host machine. It will mount the current directory as
# /app in the container, and run make from there.

set -euo pipefail
IFS=$'\t\n'

main() {
  local current_dir
  current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

  "${current_dir}/run-in-container" make "$@"
}

main "$@"
