#!/usr/bin/env bash

# This script runs a command in a docker container, so that you don't need to install
# the build tools on your host machine. It will mount the current directory as
# /app in the container, and run your command from there.

set -euo pipefail
IFS=$'\t\n'

current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
cd "${current_dir}"
image_name="yoga-wasm-build-tools:latest"

exit_with_message() {
  local message
  message="${1:-An error occurred}"
  local exit_code
  exit_code="${2:-1}"

  echo "${message}" >&2
  exit "${exit_code}"
}

# run docker or podman
docker() {
  local docker_cmd
  if command -v docker &>/dev/null; then
    docker_cmd="docker"
  elif command -v podman &>/dev/null; then
    docker_cmd="podman"
  else
    exit_with_message "Neither docker nor podman found"
  fi

  command "${docker_cmd}" "$@"
}

# run jq, possibly in a container
jq() {
  if command -v jq &>/dev/null; then
    command jq "$@"
  else
    docker run --rm -i docker.io/library/jq "$@"
  fi
}

latest_deno_version() {
  curl --fail --silent "https://api.github.com/repos/denoland/deno/releases/latest" |
    jq -r .tag_name
}

build_image() {
  DENO_VERSION="${DENO_VERSION:-$(latest_deno_version)}"

  docker build \
    --build-arg DENO_VERSION="${DENO_VERSION}" \
    --tag "${image_name}" \
    .
}

main() {
  # build the image
  build_image

  # run with a tty, if we're attached to a terminal
  local interactivity_flag
  if [[ -t 1 ]]; then
    interactivity_flag="-it"
  else
    interactivity_flag="-i"
  fi

  # run the image, mounting the current directory
  docker run \
    --rm \
    "${interactivity_flag}" \
    --env="USER_ID=$(id -u)" \
    --env="GROUP_ID=$(id -g)" \
    --env="USER_NAME=$(id -un)" \
    --env="GROUP_NAME=$(id -gn)" \
    --env="HOME=${HOME}" \
    -v "${current_dir}:${current_dir}" \
    -w "${current_dir}" \
    "${image_name}" \
    "$@"
}

main "$@"
