#!/usr/bin/env bash

set -euo pipefail
IFS=$'\t\n'

main(){
    local -r script_path="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
    local -r script_name="$(basename "${BASH_SOURCE[0]}")"
    local -r script="${script_path}/${script_name%.*}.ts"
    
    deno run \
        --allow-run \
        "${script}" \
        "$@"
}

main "$@"